<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="microBK">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="microBK" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_microBK_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_microBK"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_microBK">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/microBK/microBK.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="0.0 -0.0 -0.065" rpy="3.142 0.0 -3.142"/>
				<geometry>
					<cylinder radius="${0.007+safety_distance/2}" length="${0.048+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.061 -0.0 -0.028" rpy="3.142 1.571 0.0"/>
				<geometry>
					<box size="${0.021+safety_distance/2} ${0.074+safety_distance/2} ${0.093+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.0 -0.0 -0.007" rpy="0.0 0.0 0.0"/>
				<geometry>
					<cylinder radius="${0.007+safety_distance/2}" length="${0.016+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.069 0.004 -0.041" rpy="-2.853 1.571 -1.529"/>
				<geometry>
					<box size="${0.006+safety_distance/2} ${0.037+safety_distance/2} ${0.045+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.001 0.015 -0.027" rpy="-1.571 0.0 1.571"/>
				<geometry>
					<box size="${0.016+safety_distance/2} ${0.022+safety_distance/2} ${0.03+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.0 -0.016 -0.027" rpy="1.571 0.0 1.571"/>
				<geometry>
					<box size="${0.015+safety_distance/2} ${0.021+safety_distance/2} ${0.03+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.001 -0.001 -0.028" rpy="1.571 0.0 -1.571"/>
				<geometry>
					<box size="${0.015+safety_distance/2} ${0.026+safety_distance/2} ${0.032+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
