<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cameraD435">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="cameraD435" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_cameraD435_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_cameraD435"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_cameraD435">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/cameraD435/cameraD435.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="-0.0 0.0 -0.007" rpy="0.003 1.571 -1.571"/>
				<geometry>
					<box size="${0.015+safety_distance/2} ${0.026+safety_distance/2} ${0.091+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.0 0.001 -0.033" rpy="0.0 0.0 -1.257"/>
				<geometry>
					<cylinder radius="${0.032+safety_distance/2}" length="${0.014+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.0 0.01 -0.019" rpy="-1.57 1.571 0.0"/>
				<geometry>
					<box size="${0.01+safety_distance/2} ${0.027+safety_distance/2} ${0.112+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.001 0.049 -0.025" rpy="1.571 -1.571 0.0"/>
				<geometry>
					<box size="${0.001+safety_distance/2} ${0.026+safety_distance/2} ${0.035+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.0 -0.002 -0.025" rpy="-0.819 -1.571 0.0"/>
				<geometry>
					<box size="${0.001+safety_distance/2} ${0.064+safety_distance/2} ${0.066+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
