<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="PUprobe2">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="PUprobe2" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_PUprobe2_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_PUprobe2"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_PUprobe2">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/PUprobe2/PUprobe2.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="-0.089 0.129 0.0" rpy="1.571 0.0 -0.0"/>
				<geometry>
					<box size="${0.024+safety_distance/2} ${0.065+safety_distance/2} ${0.143+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.043 -0.003 -0.0" rpy="0.0 -1.571 0.0"/>
				<geometry>
					<box size="${0.022+safety_distance/2} ${0.023+safety_distance/2} ${0.112+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.073 0.033 -0.0" rpy="-1.571 1.571 0.0"/>
				<geometry>
					<box size="${0.027+safety_distance/2} ${0.035+safety_distance/2} ${0.049+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
