<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pencil">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="pencil" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_pencil_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_pencil"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_pencil">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/pencil/pencil.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="-0.0 0.0 -0.179" rpy="-0.0 0.0 0.0"/>
				<geometry>
					<cylinder radius="${0.032+safety_distance/2}" length="${0.008+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.0 -0.0 -0.087" rpy="3.142 0.0 -1.503"/>
				<geometry>
					<box size="${0.041+safety_distance/2} ${0.041+safety_distance/2} ${0.176+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
