joint_limits:

  panda_joint1:
    has_position_limits: true
    max_position: 2.8
    min_position: -2.8
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.75

  panda_joint2:
    has_position_limits: true
    max_position: 1.7
    min_position: -1.7
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 1.875

  panda_joint3:
    has_position_limits: true
    max_position: 2.8
    min_position: -2.8
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 2.5

  panda_joint4:
    has_position_limits: true
    max_position: -0.1
    min_position: -3.0
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.125

  panda_joint5:
    has_position_limits: true
    max_position: 2.8
    min_position: -2.8
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 3.75

  panda_joint6:
    has_position_limits: true
    max_position: 3.7
    min_position: -0.0
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 5

  panda_joint7:
    has_position_limits: true
    max_position: 2.8
    min_position: -2.8
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 5