<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="PUprobe">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="PUprobe" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_PUprobe_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_PUprobe"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_PUprobe">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/PUprobe/PUprobe.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="-0.023 0.017 -0.0" rpy="3.142 0.0 1.571"/>
				<geometry>
					<box size="${0.013+safety_distance/2} ${0.021+safety_distance/2} ${0.029+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.023 0.0 -0.061" rpy="3.142 0.0 -0.0"/>
				<geometry>
					<box size="${0.021+safety_distance/2} ${0.074+safety_distance/2} ${0.093+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.023 -0.015 0.0" rpy="3.142 0.0 1.571"/>
				<geometry>
					<box size="${0.016+safety_distance/2} ${0.021+safety_distance/2} ${0.031+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.037 -0.004 -0.069" rpy="1.32 0.004 -0.002"/>
				<geometry>
					<box size="${0.006+safety_distance/2} ${0.037+safety_distance/2} ${0.045+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.035 0.001 0.001" rpy="1.571 0.0 -1.571"/>
				<geometry>
					<box size="${0.017+safety_distance/2} ${0.032+safety_distance/2} ${0.091+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
