<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="microGRAS_alternate">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="microGRAS_alternate" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_microGRAS_alternate_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_microGRAS_alternate"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_microGRAS_alternate">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/microGRAS_alternate/microGRAS_alternate.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="-0.155 0.0 -0.104" rpy="-3.142 1.571 0.0"/>
				<geometry>
					<box size="${0.024+safety_distance/2} ${0.065+safety_distance/2} ${0.093+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.0 0.0 -0.086" rpy="0.0 0.0 -1.571"/>
				<geometry>
					<box size="${0.027+safety_distance/2} ${0.029+safety_distance/2} ${0.175+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.061 0.0 -0.12" rpy="3.142 0.0 -1.571"/>
				<geometry>
					<box size="${0.027+safety_distance/2} ${0.093+safety_distance/2} ${0.097+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
