<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="marker2D">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="marker2D" params="connected_to:='' robot_name:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">

    <xacro:unless value="${connected_to == ''}">
      <joint name="${robot_name}_marker2D_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${robot_name}_marker2D"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>

    <link name="${robot_name}_marker2D">
      <visual>
        <geometry>
          <mesh filename="file://$(find robot_arm_tools)/config/tools/marker2D/marker2D.stl"/>
        </geometry>
      </visual>
			<collision>
				<origin xyz="0.0 0.001 -0.007" rpy="0.0 0.0 0.0"/>
				<geometry>
					<cylinder radius="${0.033+safety_distance/2}" length="${0.009+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.012 0.001 -0.0" rpy="0.731 1.571 2.302"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.038+safety_distance/2} ${0.062+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.042 0.052 0.0" rpy="1.76 1.57 2.356"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.031+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.026 -0.049 0.0" rpy="1.991 1.57 0.464"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.038+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.035 0.049 0.0" rpy="-1.997 1.571 0.0"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.044+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="-0.031 -0.044 -0.0" rpy="-0.023 1.561 -2.083"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.056+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.02 0.007 -0.0" rpy="1.571 1.571 0.0"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.027+safety_distance/2} ${0.075+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.051 0.018 0.0" rpy="0.183 1.571 0.0"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.033+safety_distance/2}"/>
				</geometry>
			</collision>
			<collision>
				<origin xyz="0.043 -0.016 0.0" rpy="-0.464 1.571 0.0"/>
				<geometry>
					<box size="${0.005+safety_distance/2} ${0.014+safety_distance/2} ${0.018+safety_distance/2}"/>
				</geometry>
			</collision>
    </link>
    
  </xacro:macro>
</robot>
